accounts/models.py
from datetime import datetime

from flask_login import UserMixin

from proj import bcrypt, db


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    is_confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(
        self, email, password, is_admin=False, is_confirmed=False, confirmed_on=None
    ):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.created_on = datetime.now()
        self.is_admin = is_admin
        self.is_confirmed = is_confirmed
        self.confirmed_on = confirmed_on

    def __repr__(self):
        return f"<email {self.email}>"

accounts/forms.py
import pathlib

from decouple import config
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from accounts.models import User


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

accounts/utils/auth.py
import pathlib
from functools import wraps

from decouple import config
from flask import request, current_app, render_template
from flask_login import current_user
from flask_login.config import EXEMPT_METHODS


def authorize_user(email):
    if not email:
        return None
    items = pathlib.Path(config("AUTH_USERS_FILE_PATH")).open("r").readlines()
    items = list(map(lambda x: x.replace("\n", ""), items))
    if email not in items:
        return False
    return True


def login_required(func):
    """
    If you decorate a view with this, it will ensure that the current user is
    logged in and authenticated before calling the actual view. (If they are
    not, it calls the :attr:`LoginManager.unauthorized` callback.) For
    example::

        @app.route('/post')
        @login_required
        def post():
            pass

    If there are only certain times you need to require that your user is
    logged in, you can do so with::

        if not current_user.is_authenticated:
            return current_app.login_manager.unauthorized()

    ...which is essentially the code that this function adds to your views.

    It can be convenient to globally turn off authentication when unit testing.
    To enable this, if the application configuration variable `LOGIN_DISABLED`
    is set to `True`, this decorator will be ignored.

    .. Note ::

        Per `W3 guidelines for CORS preflight requests
        <http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0>`_,
        HTTP ``OPTIONS`` requests are exempt from login checks.

    :param func: The view function to decorate.
    :type func: function
    """

    @wraps(func)
    def decorated_view(*args, **kwargs):
        if request.method in EXEMPT_METHODS or current_app.config.get("LOGIN_DISABLED"):
            pass
        elif not current_user.is_authenticated:
            return current_app.login_manager.unauthorized()  # noqa
        elif current_user.is_authenticated:
            if not authorize_user(current_user.email):
                return render_template("errors/403.html")

        # flask 1.x compatibility
        # current_app.ensure_sync is only available in Flask >= 2.0
        if callable(getattr(current_app, "ensure_sync", None)):
            return current_app.ensure_sync(func)(*args, **kwargs)
        return func(*args, **kwargs)

    return decorated_view

accounts/views.py
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from proj import bcrypt, db
from accounts.models import User
from accounts.token import confirm_token, generate_token
from .utils.decorators import logout_required
from .utils.email import send_email
from .forms import LoginForm, RegisterForm

accounts_bp = Blueprint("accounts", __name__)


@accounts_bp.route("/register", methods=["GET", "POST"])
@logout_required
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        token = generate_token(user.email)
        confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
        html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash("A confirmation email has been sent via email.", "success")
        return redirect(url_for("accounts.inactive"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
@logout_required
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for("index"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/confirm/<token>")
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash("Account already confirmed.", "success")
        return redirect(url_for("index"))
    email = confirm_token(token)
    user = User.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash("You have confirmed your account. Thanks!", "success")
    else:
        flash("The confirmation link is invalid or has expired.", "danger")
    return redirect(url_for("index"))


@accounts_bp.route("/inactive")
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for("index"))
    return render_template("accounts/inactive.html")


@accounts_bp.route("/resend")
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash("Your account has already been confirmed.", "success")
        return redirect(url_for("index"))
    token = generate_token(current_user.email)
    confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
    html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash("A new confirmation email has been sent.", "success")
    return redirect(url_for("accounts.inactive"))

templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Automate - EcoSmart Solutions, Inc.</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename="styles.css")}}">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
           {{message}}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
        <div class="col-md-4"></div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" type="text/javascript"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}

  </body>
</html>

templates/accounts/confirm_email.html
<p>
  Welcome! Thanks for signing up. Please follow this link to activate your
  account:
</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br />
<p>Cheers!</p>

templates/accounts/inactive.html
{% extends "_base.html" %} {% block content %}

<div class="text-center">
  <h1>Welcome!</h1>
  <br />
  <p>
    You have not confirmed your account. Please check your inbox (and your spam
    folder) - you should have received an email with a confirmation link.
  </p>
  <p>
    Didn't get the email?
    <a href="{{ url_for('accounts.resend_confirmation') }}">Resend</a>.
  </p>
</div>

{% endblock %}

templates/accounts/login.html
{% extends "_base.html" %}

{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <main class="form-signin w-100 m-auto">
      <form role="form" method="post" action="">
        {{ form.csrf_token }}
        <h1 class="h3 mb-3 fw-normal text-center">Please sign in</h1>

        <div class="form-floating">
          {{ form.email(placeholder="email", class="form-control mb-2") }}
          {{ form.email.label }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.password(placeholder="password", class="form-control mb-2") }}
          {{ form.password.label }}
            {% if form.password.errors %}
              {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <p class="text-center mt-3">New User? <a href="{{ url_for('accounts.register') }}">Register now</a></p>
      </form>
    </main>
  </div>
  <div class="col-md-4"></div>
</div>

{% endblock %}

templates/accounts/register.html
{% extends "_base.html" %}

{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <main class="form-signin w-100 m-auto">
      <form role="form" method="post" action="">
        {{ form.csrf_token }}
        <h1 class="h3 mb-3 fw-normal text-center">Please register</h1>

        <div class="form-floating">
          {{ form.email(placeholder="email", class="form-control mb-2") }}
          {{ form.email.label }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.password(placeholder="password", class="form-control mb-2") }}
          {{ form.password.label }}
            {% if form.password.errors %}
              {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.confirm(placeholder="Confirm Password", class="form-control mb-2") }}
          {{ form.confirm.label }}
            {% if form.confirm.errors %}
              {% for error in form.confirm.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
        <p class="text-center mt-3">Already registered? <a href="{{ url_for('accounts.login') }}">Login now</a></p>
      </form>
    </main>
  </div>
  <div class="col-md-4"></div>
</div>

{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Automate - EcoSmart Solutions, Inc.</title>

    <script src="{{ url_for('static', filename='lib/axios.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/lodash.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/sweetalert2.all.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/ag-grid-community.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/grid.js') }}"></script>
    <script src="{{ url_for('static', filename='js/new_project_dialog.js') }}"></script>
    <script src="{{ url_for('static', filename='js/project_buttons.js') }}"></script>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/lds-spinner.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}"/>

    <script type="text/javascript">
        window.projectsPath = "{{ PROJECTS_FOLDER }}";
        window.PATH_COLUMN = "{{ PATH_COLUMN }}";
    </script>
</head>
<body>
<div style="margin: 0 20px">
    <div style="display: flex; justify-content: space-between; align-items: center">
        <div style="display: flex;">
            <div>
                <div class="dropdown">
                    <button class="dropbtn">
                        Add Project
                    </button>
                    <div class="dropdown-content">
                        <a href="#" id="newProject" target="_blank">Select Root folder</a>
                        <a href="#" target="_blank">Select Client Folder</a>
                        <a href="#" target="_blank">Select Project Folder</a>
                    </div>

                </div>
                     
                <!-- <a href="#" id="newProject" target="_blank"><img
                        src="{{ url_for('static', filename='images/excel.png') }}" title="New Project"></a> -->
                <!-- <div>New Project</div> -->
                <input id="newProjectFile" type="file" style="display: none;"/>
            </div>
            
            <div class="button-group audit-buttons">
                <div class="excel-processor-button">
                    <a href="#" id="reprocessAuditReport" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}" title="Process Audit Report"></a>
                    <div>Audit Process</div>
                </div>

                <div class="excel-processor-button">
                    <a href="#" id="processAuditReportStandalone" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}"
                            title="Process Audit Report (standalone)"></a>
                    <div>Audit Custom</div>
                    <input id="auditReportFileStandalone" type="file" style="display: none;"/>
                </div>

                <div class="excel-processor-button">
                    <a href="#" id="processAuditReportWithDefaults" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}"
                            title="Process Audit Report (restore defaults)"></a>
                    <div>Audit Defaults</div>
                </div>
            </div>

            <div class="button-group proposal-buttons">
                <div class="excel-processor-button">
                    <a href="#" id="createProposalPDF" target="_blank"><img src="{{
                            url_for('static', filename='images/excel.png') }}" title="Proposal"></a>
                    <div>Proposal</div>
                </div>

                <div class="excel-processor-button">
                    <a href="#" id="createCustomProposal" target="_blank"><img src="{{
                            url_for('static', filename='images/excel.png') }}" title="Custom Proposal"></a>
                    <div>Proposal Custom</div>
                    <input id="proposalCustomFile" type="file" style="display: none;"/>
                </div>
            </div>

            <div class="excel-processor-button">
                <a href="#" id="createPhotosCheckList" target="_blank"><img
                        src="{{ url_for('static', filename='images/excel.png') }}" title="Create Photos Check List"></a>
                <div>Photos</div>
                <input id="photosCheckListFile" type="file" style="display: none;"/>
            </div>

            <div class="button-group scope-buttons">
                <!-- <div class="excel-processor-button">
                    <a href="#" id="createProjectScopePDF" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}" title="Crete Scope PDF (project)"></a>
                    <div>Scope Proposal</div>
                </div>

                <div class="excel-processor-button">
                    <a href="#" id="createScopePDF" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}" title="Crete Scope PDF (custom)"></a>
                    <div>Scope Custom</div>
                    <input id="scopeFile" type="file" style="display: none;"/>
                </div> -->
				
                <div class="excel-processor-button">
                    <a href="#" id="createScopePDFv2" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}" title="Create Scope PDF v2"></a>
                    <div>Scope v2</div>
                </div>				
            </div>

            <div class="excel-processor-button">
                <a href="#" id="createCLIP" target="_blank"><img
                        src="{{ url_for('static', filename='images/excel.png') }}" title="Crete CLIP"></a>
                <div>CLIP</div>
            </div>

            <div class="button-group materials-buttons">
                <div class="excel-processor-button">
                    <a href="#" id="createMaterials" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}" title="Create Materials"></a>
                    <div>Materials</div>
                </div>

                <!-- <div class="excel-processor-button">
                    <a href="#" id="createMaterialsCombined" target="_blank"><img
                            src="{{ url_for('static', filename='images/excel.png') }}" title="Create Combined Materials"></a>
                    <div>Materials Combined</div>
                </div> -->
            </div>

			<div class="excel-processor-button">
				<a href="#" id="createPurchaseOrder" target="_blank"><img
						src="{{ url_for('static', filename='images/excel.png') }}" title="Create Purchase Order">
				</a>
				<div>Purchase Order</div>
			</div>				

			<div class="excel-processor-button">
				<a href="#" id="createCustomerInvoice" target="_blank">
					<img src="{{ url_for('static', filename='images/excel.png') }}" title="Create Customer Invoice">
				</a>
				<div>Customer Invoice</div>
			</div>			

            <div class="excel-processor-button">
                <a href="#" id="createPDFLink" target="_blank">
                    <img src="{{ url_for('static', filename='images/pdf.png') }}" alt="Disclaimer IP">
                </a>
                <div>Disclaimer IP</div>
            </div>

              <div class="excel-processor-button">
                <a href="#" id="imageCompression" target="_blank">
                  <img src="{{ url_for('static', filename='images/zip.png') }}" alt="Image Compression">
                </a>
                <div>Image Compression</div>
              </div>

        </div>

        <div id="dataChanged" style="font-size: 1.2em; display: none">
            <strong>Changes were made</strong> <a href="javascript:void(0)" id="save_link">Save</a> <a
                href="/">Cancel</a>
        </div>

        <div style="display: grid; grid-auto-flow: column; grid-gap: 10px">
            <a id="show_hide_link" href="javascript:void(0)">Show/hide columns</a> <a id="reset_link"
                                                                                      href="javascript:void(0)">Reset
            columns config</a> <a href="javascript:void(0)" id="add_row_link">Add row</a>
        </div>
        <div id="show_logout_link" style="font-size: 1.2em;">
            <a style="color: red" href="/logout" id="logout_link">Logout</a>
        </div>
    </div>

    <div id="grid" style="height: 850px; width:100%;" class="ag-theme-alpine grid"></div>

    <dialog id="new-project-dialog">
        <h3 id="new-project-dialog-title">Create New Project</h3>
        <div class="options-section">
            <label for="option-delay">Projects folder: &nbsp;</label>
            <input type="text" id="projects-folder"/>
        </div>

        <div class="options-section dialog-buttons">
            <input type="button" id="create-new-project-cancel" value="Cancel"/>
            &nbsp;
            <input type="button" id="create-new-project-button" value="Create"/>
        </div>
    </dialog>
</div>

<div id="base-loading-shim" style="display: none">
    <div class="lds-spinner">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
    <br>
    <!--h1 style="font-size: 40px">Saving to Excel. Don't close this page...</h1-->
</div>

</body>
</html>

templates/navigation.html
<!-- Navigation -->
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('index') }}" class="nav-link px-2 text-secondary">Home</a></li>
      </ul>

      <div class="text-end">
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('accounts.logout') }}"><button type="button" class="btn btn-danger me-2">Logout</button></a>
        {% else %}
          <a href="{{ url_for('accounts.login') }}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
          <a href="{{ url_for('accounts.register') }}"><button type="button" class="btn btn-success">Sign up</button></a>
        {% endif %}
          
      </div>
    </div>
  </div>
</header>